Repository Bigeco/Invaders, pull requests merged in 2023-12, with the labels that each got.

#214 SI-66 refactor: rename non-conventional variable names
  src/screen/HighScoreScreen.java
Labels: :recycle:refactor

#204 SI-68 fix: resolve AssignmentToNonFinalStatic in every file
  src/effect/Effect.java
  src/engine/BGM.java
  src/engine/DrawManager.java
  src/engine/FileManager.java
  src/engine/InputManager.java
  src/screen/GameScreen.java
  src/screen/GameScreen_2P.java
Labels: :hammer_and_wrench:fix

#216 SI-66 refactor: rename unconventional variable names
  src/effect/Effect.java
  src/effect/ShipEffect.java
  src/engine/BGM.java
  src/engine/Core.java
  src/engine/CountUpTimer.java
  src/engine/DrawManager.java
  src/engine/EnhanceManager.java
  src/engine/GameState.java
  src/engine/GameState_2P.java
  src/engine/ItemManager.java
  src/engine/SoundEffect.java
  src/entity/EnemyShipFormation.java
  src/entity/Item.java
  src/entity/ItemPool.java
  src/entity/Laser.java
  src/entity/Ship.java
  src/screen/EnhanceScreen.java
  src/screen/EnhanceScreen_2P.java
  src/screen/GameScreen.java
  src/screen/GameScreen_2P.java
  src/screen/RandomBoxScreen.java
  src/screen/RandomBoxScreen_2P.java
  src/screen/SkinStoreScreen.java
  src/screen/StageSelectScreen.java
  src/screen/StoreScreen.java
  src/screen/StoreScreen_2P.java
  src/screen/SubMenuScreen_2P.java
  src/screen/TwoPlayHighScoreScreen.java
Labels: :recycle:refactor

#218 SI-217 fix: fix multiple bullets were fired
  src/effect/ShipEffect.java
Labels: :bug:bug, :hammer_and_wrench:fix

#222 SI-66 refactor: rename unconventional method names
  src/engine/BGM.java
  src/engine/Core.java
  src/engine/DrawManager.java
  src/engine/GameState.java
  src/engine/GameState_2P.java
  src/engine/SoundEffect.java
  src/entity/EnemyShipFormation.java
  src/entity/Item.java
  src/entity/Laser.java
  src/screen/EnhanceScreen_2P.java
  src/screen/GameScreen.java
  src/screen/GameScreen_2P.java
  src/screen/HighScoreScreen.java
  src/screen/RecoveryPaymentScreen_2P.java
  src/screen/StoreScreen_2P.java
  src/screen/TwoPlayHighScoreScreen.java
  src/screen/TwoPlayScoreScreen.java
Labels: :recycle:refactor

#225 SI-66 refactor: rename unconventional method and variable names
  src/engine/Core.java
  src/engine/DrawManager.java
  src/engine/InputManager.java
  src/engine/MinimalFormatter.java
  src/entity/EnemyShip.java
  src/screen/EnhanceScreen.java
  src/screen/EnhanceScreenRecovery.java
  src/screen/EnhanceScreen_2P.java
  src/screen/GameScreen.java
  src/screen/GameScreen_2P.java
  src/screen/RandomBoxScreen.java
  src/screen/RandomBoxScreen_2P.java
  src/screen/RandomRewardScreen.java
  src/screen/RandomRewardScreen_2P.java
  src/screen/RecoveryPaymentScreen.java
  src/screen/RecoveryPaymentScreen_2P.java
  src/screen/RecoveryScreen.java
  src/screen/ScoreMenuScreen.java
  src/screen/ScoreScreen.java
  src/screen/Screen.java
  src/screen/SelectScreen.java
  src/screen/SkinStoreScreen.java
  src/screen/StoreScreen.java
  src/screen/StoreScreen_2P.java
  src/screen/SubMenuScreen.java
  src/screen/SubMenuScreen_2P.java
  src/screen/TitleScreen.java
  src/screen/TwoPlayScoreScreen.java
Labels: :recycle:refactor

#226 Revert "SI-66 refactor: rename unconventional method and variable names"
  src/engine/Core.java
  src/engine/DrawManager.java
  src/engine/InputManager.java
  src/engine/MinimalFormatter.java
  src/entity/EnemyShip.java
  src/screen/EnhanceScreen.java
  src/screen/EnhanceScreenRecovery.java
  src/screen/EnhanceScreen_2P.java
  src/screen/GameScreen.java
  src/screen/GameScreen_2P.java
  src/screen/RandomBoxScreen.java
  src/screen/RandomBoxScreen_2P.java
  src/screen/RandomRewardScreen.java
  src/screen/RandomRewardScreen_2P.java
  src/screen/RecoveryPaymentScreen.java
  src/screen/RecoveryPaymentScreen_2P.java
  src/screen/RecoveryScreen.java
  src/screen/ScoreMenuScreen.java
  src/screen/ScoreScreen.java
  src/screen/Screen.java
  src/screen/SelectScreen.java
  src/screen/SkinStoreScreen.java
  src/screen/StoreScreen.java
  src/screen/StoreScreen_2P.java
  src/screen/SubMenuScreen.java
  src/screen/SubMenuScreen_2P.java
  src/screen/TitleScreen.java
  src/screen/TwoPlayScoreScreen.java
Labels: :bug:bug
