Repository Bigeco/Invaders, pull requests merged in 2023-11, with the labels that each got.

#167 SI-24 feat: change size of screen (x1.1)
  src/engine/Core.java
Labels: :sparkles:feature

#170 SI-7 Change Game Screen UI(HUD)
  res/graphics
  src/engine/DrawManager.java
  src/screen/EnhanceScreen.java
  src/screen/EnhanceScreen_2P.java
  src/screen/GameScreen.java
  src/screen/GameScreen_2P.java
  src/screen/SkinStoreScreen.java
  src/screen/StoreScreen.java
  src/screen/StoreScreen_2P.java
Labels: :sparkles:feature, :lipstick:design

#172 SI-11 design: change the color and position of the clear text
  src/engine/DrawManager.java
Labels: :lipstick:design

#173 SI-36 feat:add life plus item in game
  res/graphics
  src/engine/DrawManager.java
  src/engine/GameState.java
  src/entity/Item.java
  src/screen/GameScreen.java
Labels: :sparkles:feature

#175 SI-16 feat: add EnhanceScreen_recovery class
  src/engine/DrawManager.java
  src/screen/EnhanceScreenRecovery.java
Labels: :sparkles:feature

#179 SI-16 Enhance after recovery
  src/engine/Core.java
  src/engine/DrawManager.java
  src/screen/EnhanceScreenRecovery.java
Labels: :sparkles:feature

#192 SI-30 feature: add coin sound
  sound/soundEffect/usecoin.wav
  src/engine/DrawManager.java
  src/engine/SoundEffect.java
  src/screen/SkinStoreScreen.java
  src/screen/StoreScreen.java
Labels: :sparkles:feature

#193 SI-39 feature: add enhanced sound
  sound/soundEffect/enhancedDestruction.wav
  src/engine/EnhanceManager.java
  src/engine/SoundEffect.java
  src/screen/GameScreen.java
Labels: :sparkles:feature
